version: '3.3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=104.197.223.37
    ports:
      - "8080:80"
    volumes:
      - ./config/phpmyadmin/config.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_web
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/mysql/app.cnf:/etc/mysql/conf.d/app.cnf
      - ./config/mysql/initdb.d/:/docker-entrypoint-initdb.d/
#    ports:
#      - "3306:3306"
#  backend-nginx:
#    image: anhmantk/backend-nginx
  backend-php:
    image: anhmantk/backend-php
volumes:
  mysql-data:
    driver: local